In [1]:
import pandas as pd
df = pd.read_csv('naive_bayes_spam_practice.csv')
df.head()

  category                                            message
0      ham  Hey, are we still meeting for lunch at 10:00 A...
1     spam  Double your money in 24 hours with crypto trad...
2     spam  Exclusive offer! Get cheap loan approval today...
3     spam  WINNER! Guarantee high return investment. Repl...
4      ham  Can you give me a call when you are free? Need...

In [2]:
df.groupby('category').describe()

         message                                                            \
           count unique                                                top
category
ham          150     16  Can you give me a call when you are free? Need...
spam         100     14  WINNER! Guarantee high return investment. Repl...


         freq
category
ham        28
spam       18

In [3]:
df['spam'] = df['category'].apply(lambda x: 1 if x == 'spam' else 0)
df.head()

  category                                            message  spam
0      ham  Hey, are we still meeting for lunch at 10:00 A...     0
1     spam  Double your money in 24 hours with crypto trad...     1
2     spam  Exclusive offer! Get cheap loan approval today...     1
3     spam  WINNER! Guarantee high return investment. Repl...     1
4      ham  Can you give me a call when you are free? Need...     0

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.message, df.spam, test_size=0.25)

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [7]:
emails =['Hey mohan, can we get toghether to discuss about the project? I have some ideas to share with you.',
         'Congratulations! you have won a lottery of $1,000,000. Please send us your bank details to claim your prize.']
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [8]:
X_test_count = v.transform(X_test)
model.score(X_test_count, y_test)

1.0

In [9]:
from sklearn.pipeline import Pipeline
clf = Pipeline([('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [10]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [11]:
clf.score(X_test, y_test)

1.0

In [12]:
clf.predict(emails)

array([0, 1])