Working with categorical data and organizing them using one hot encoder

Importing libraries

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("housing_categorical_practice.csv")
df

            town  area   price
0    Springfield  1355  317383
1    Springfield  2431  453231
2    Springfield  1567  330162
3    Springfield  1896  348820
4      Riverdale  2608  554642
..           ...   ...     ...
295  Springfield  2378  438308
296  Springfield  2147  411885
297    Riverdale  2241  555049
298      Oakwood  1766  270935
299    Riverdale  3349  681603

[300 rows x 3 columns]

In [3]:
dummies = pd.get_dummies(df['town'], dtype= int)
dummies

     Oakwood  Riverdale  Springfield
0          0          0            1
1          0          0            1
2          0          0            1
3          0          0            1
4          0          1            0
..       ...        ...          ...
295        0          0            1
296        0          0            1
297        0          1            0
298        1          0            0
299        0          1            0

[300 rows x 3 columns]

In [4]:
merged = pd.concat([df,dummies], axis = 'columns')
merged

            town  area   price  Oakwood  Riverdale  Springfield
0    Springfield  1355  317383        0          0            1
1    Springfield  2431  453231        0          0            1
2    Springfield  1567  330162        0          0            1
3    Springfield  1896  348820        0          0            1
4      Riverdale  2608  554642        0          1            0
..           ...   ...     ...      ...        ...          ...
295  Springfield  2378  438308        0          0            1
296  Springfield  2147  411885        0          0            1
297    Riverdale  2241  555049        0          1            0
298      Oakwood  1766  270935        1          0            0
299    Riverdale  3349  681603        0          1            0

[300 rows x 6 columns]

In [5]:
final = merged.drop(['town', 'Oakwood'], axis='columns')
final

     area   price  Riverdale  Springfield
0    1355  317383          0            1
1    2431  453231          0            1
2    1567  330162          0            1
3    1896  348820          0            1
4    2608  554642          1            0
..    ...     ...        ...          ...
295  2378  438308          0            1
296  2147  411885          0            1
297  2241  555049          1            0
298  1766  270935          0            0
299  3349  681603          1            0

[300 rows x 4 columns]

In [6]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [7]:
X = final.drop('price', axis='columns')
X

     area  Riverdale  Springfield
0    1355          0            1
1    2431          0            1
2    1567          0            1
3    1896          0            1
4    2608          1            0
..    ...        ...          ...
295  2378          0            1
296  2147          0            1
297  2241          1            0
298  1766          0            0
299  3349          1            0

[300 rows x 3 columns]

In [8]:
y = final.price
y

0      317383
1      453231
2      330162
3      348820
4      554642
        ...
295    438308
296    411885
297    555049
298    270935
299    681603
Name: price, Length: 300, dtype: int64

In [9]:
model.fit(X,y)

LinearRegression()

In [10]:
model.predict(pd.DataFrame(
    [[2800, 1, 0]],
    columns=X.columns
))

array([602263.41480539])

In [11]:
model.score(X,y)

0.9800697834113482

In [29]:
df

     town  area   price
0       2  1355  317383
1       2  2431  453231
2       2  1567  330162
3       2  1896  348820
4       1  2608  554642
..    ...   ...     ...
295     2  2378  438308
296     2  2147  411885
297     1  2241  555049
298     0  1766  270935
299     1  3349  681603

[300 rows x 3 columns]

In [13]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [14]:
dfle = df
dfle.town = le.fit_transform(dfle.town)
dfle

     town  area   price
0       2  1355  317383
1       2  2431  453231
2       2  1567  330162
3       2  1896  348820
4       1  2608  554642
..    ...   ...     ...
295     2  2378  438308
296     2  2147  411885
297     1  2241  555049
298     0  1766  270935
299     1  3349  681603

[300 rows x 3 columns]

In [15]:
X = dfle[['town', 'area']]. values
X

array([[   2, 1355],
       [   2, 2431],
       [   2, 1567],
       [   2, 1896],
       [   1, 2608],
       [   2, 1436],
       [   1, 1885],
       [   1, 1927],
       [   1, 1899],
       [   2, 1559],
       [   2, 1586],
       [   0, 1646],
       [   2, 2911],
       [   2, 2095],
       [   2, 1396],
       [   2, 1615],
       [   2, 1347],
       [   0, 1196],
       [   2, 2032],
       [   1, 1780],
       [   0,  947],
       [   2, 1357],
       [   1, 2617],
       [   1, 2380],
       [   0, 1848],
       [   1,  890],
       [   2, 1232],
       [   1, 2090],
       [   1, 1805],
       [   2, 1476],
       [   0, 1550],
       [   0, 1241],
       [   0, 1811],
       [   0, 1189],
       [   2, 2309],
       [   0, 1401],
       [   1, 2002],
       [   2, 1735],
       [   1, 1728],
       [   0,  824],
       [   2, 1840],
       [   1, 2103],
       [   2, 1935],
       [   2, 2257],
       [   2, 1479],
       [   1, 2493],
       [   2, 1602],
       [   2, 1839],
       [   1, 2204],
       [   2, 1375],
       [   1, 2510],
       [   2, 1486],
       [   0, 1292],
       [   1, 2313],
       [   1, 2037],
       [   0, 1477],
       [   2, 2319],
       [   0, 1475],
       [   1, 2313],
       [   2, 1917],
       [   2, 1869],
       [   1, 1604],
       [   1, 1824],
       [   1, 2681],
       [   1, 1766],
       [   2, 1444],
       [   0, 1663],
       [   1, 2206],
       [   1, 1496],
       [   1, 1664],
       [   0, 1362],
       [   0, 1145],
       [   0, 1122],
       [   1, 2286],
       [   1, 2315],
       [   0, 1417],
       [   0, 1661],
       [   1, 1511],
       [   0, 1491],
       [   0, 1554],
       [   0, 1799],
       [   0, 1305],
       [   2, 1866],
       [   2, 2725],
       [   2, 1634],
       [   2, 1611],
       [   2, 2424],
       [   2, 1507],
       [   2, 2755],
       [   1, 1187],
       [   0, 1266],
       [   2, 2001],
       [   1, 2032],
       [   2, 2506],
       [   1, 2388],
       [   1, 1440],
       [   2, 1705],
       [   2,  503],
       [   2, 1002],
       [   1, 1979],
       [   2, 1823],
       [   0, 1105],
       [   2, 1719],
       [   1, 2256],
       [   2, 1553],
       [   1, 2124],
       [   0, 1254],
       [   2, 1564],
       [   2, 2180],
       [   0, 1643],
       [   2, 2020],
       [   0, 1393],
       [   2, 1532],
       [   0, 1334],
       [   0, 1277],
       [   0, 1791],
       [   2, 1704],
       [   2, 1929],
       [   0, 1973],
       [   1, 1696],
       [   1, 2585],
       [   0, 1396],
       [   2,  963],
       [   0, 1152],
       [   2, 2045],
       [   2, 1897],
       [   2, 2023],
       [   2, 1220],
       [   0, 1200],
       [   2, 1924],
       [   1, 2048],
       [   1, 2361],
       [   1, 2446],
       [   2, 2076],
       [   2, 1827],
       [   0, 1429],
       [   0, 2082],
       [   1, 3276],
       [   1, 2144],
       [   1, 1780],
       [   1, 2716],
       [   2, 1936],
       [   2, 2028],
       [   2, 1271],
       [   0, 1377],
       [   0,  886],
       [   0, 1482],
       [   1, 1402],
       [   2, 1903],
       [   0, 1401],
       [   0, 1306],
       [   2, 1848],
       [   2, 2224],
       [   2, 1932],
       [   1, 2257],
       [   0, 2018],
       [   0, 1093],
       [   2, 2058],
       [   1, 1983],
       [   2, 2223],
       [   2, 2154],
       [   2, 2400],
       [   2, 2192],
       [   0,  888],
       [   1, 2196],
       [   2, 1278],
       [   2, 1359],
       [   2, 1774],
       [   1, 1976],
       [   2, 1587],
       [   2, 1226],
       [   2, 2585],
       [   2, 2005],
       [   2, 1755],
       [   0, 1179],
       [   2, 1689],
       [   1, 1886],
       [   1, 2488],
       [   1, 1713],
       [   1, 1396],
       [   2, 1725],
       [   2, 1541],
       [   2, 1887],
       [   1, 2196],
       [   2, 2749],
       [   1, 1681],
       [   2, 2358],
       [   1, 1500],
       [   2, 1616],
       [   2, 1563],
       [   2,  798],
       [   0, 1328],
       [   0, 1471],
       [   2, 2000],
       [   0, 2012],
       [   2, 1534],
       [   2, 1911],
       [   2, 1903],
       [   2, 1344],
       [   1, 1874],
       [   2, 1559],
       [   1, 2464],
       [   1, 1314],
       [   0, 1511],
       [   0, 1546],
       [   0, 1501],
       [   2, 1672],
       [   0, 1486],
       [   2, 1691],
       [   0,  788],
       [   1, 2725],
       [   1, 2363],
       [   2, 2156],
       [   1, 1460],
       [   2, 2003],
       [   1, 2290],
       [   2, 1363],
       [   1, 2235],
       [   0, 1295],
       [   0, 1319],
       [   0, 1271],
       [   1, 2634],
       [   1, 1383],
       [   2, 1088],
       [   1, 2290],
       [   1, 2254],
       [   1, 2308],
       [   2, 2552],
       [   1, 2291],
       [   0, 1103],
       [   0, 2161],
       [   2, 1736],
       [   0, 1655],
       [   0, 1013],
       [   1, 1448],
       [   1, 2077],
       [   1, 2602],
       [   2, 2539],
       [   2, 1393],
       [   0, 1319],
       [   2, 1800],
       [   1, 2206],
       [   2, 1754],
       [   2, 1786],
       [   1, 2894],
       [   1, 2823],
       [   2, 1915],
       [   0,  977],
       [   1, 2019],
       [   2, 2174],
       [   2, 1518],
       [   1, 1937],
       [   1, 2024],
       [   2, 2084],
       [   0, 1893],
       [   2, 2037],
       [   2, 1132],
       [   0, 1243],
       [   2, 2326],
       [   2, 1287],
       [   1, 1323],
       [   0, 1236],
       [   0, 1691],
       [   0, 1290],
       [   2, 2662],
       [   2, 1868],
       [   0, 1013],
       [   2, 1878],
       [   2, 2602],
       [   0, 1476],
       [   1, 1698],
       [   0,  847],
       [   1, 2025],
       [   1, 1894],
       [   2, 2336],
       [   2, 1420],
       [   1, 2247],
       [   2, 1569],
       [   1, 1355],
       [   0, 1389],
       [   1, 1421],
       [   0, 1589],
       [   2, 1094],
       [   2, 1770],
       [   2, 2225],
       [   1, 2479],
       [   1, 1973],
       [   1, 2414],
       [   2, 2127],
       [   2, 1367],
       [   0, 1738],
       [   0, 1681],
       [   2, 1237],
       [   2, 1888],
       [   2, 1695],
       [   2, 2378],
       [   2, 2147],
       [   1, 2241],
       [   0, 1766],
       [   1, 3349]])

In [16]:
y = dfle.price
y

0      317383
1      453231
2      330162
3      348820
4      554642
        ...
295    438308
296    411885
297    555049
298    270935
299    681603
Name: price, Length: 300, dtype: int64

In [17]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [18]:
X = ohe.fit_transform(X).toarray()
X

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.]], shape=(300, 274))

In [19]:
X = X[:,1:]
X

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 1.]], shape=(300, 273))

In [28]:
model.fit(X,y)

LinearRegression()

In [22]:
model.fit(final.drop('price', axis='columns'), final.price)

model.predict(pd.DataFrame(
    [[2800, 1, 0]],
    columns=['area', 'Riverdale', 'Springfield']
))

array([602263.41480539])

In [23]:
import pickle

In [25]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [26]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [27]:
mp.predict([[5000, 1, 0]])

c:\Users\boogey\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([874707.27921315])